### ISSUE TITLE
Python - service.accounts().reports() - v2.0 - Pulling CSV

### ISSUE THREAD

**Issue by xvrdm** [googleads/googleads-adxseller-examples#1]
Hi Google team,

Is it possible that there is a problem with the export of CSV file via the API?
I tried to add `alt='csv'` in my request but that does not change anything to my output. 

So:

```
result = service.accounts().reports().generate(
    id, query, sort,
    alt='csv').execute()
```

returns the same json-like object as 

```
result = service.accounts().reports().generate(
    id, query, sort,
    alt='json').execute()
```

Any other paramater in `alt` throw back an expected:

```
Parameter "alt" value "csv2" is not an allowed value in "[u'csv', u'json']"
```

Thanks a lot
Xavier

**Comment by cmac4603** [comment]
Hi @lukiesd I would have thought this is an open issue still, as the library throws an exception if alt is neither 'csv' nor 'json', but only ever returns json. If "json-centric", then the 'csv' option should be removed, no?
