### ISSUE TITLE
Running large reports - Ad Exchange seller REST API

### ISSUE THREAD

**Issue by snehakavinkar** [googleads/googleads-adxseller-examples#4]
Can anyone please provide working example for running large reports with Ad Exchange seller REST API in .NET using alt='media' as parameter

**Comment by lukiesd** [comment]
Hi there, we don't have examples for doing that.
You could take a look at the .Net client library here to get some guidance - https://developers.google.com/api-client-library/dotnet/apis/adexchangeseller/v2.0
