### ISSUE TITLE
Multiple arguments in filter when generating reports

### ISSUE THREAD

**Issue by jatinshah** [googleads/googleads-adxseller-examples#6]
How do I introduce multiple OR filters in service.accounts().reports().generate()?

**Comment by DeanLukies** [comment]
Please take a look at https://developers.google.com/ad-exchange/seller-rest/filters#combiningFilters

**Comment by jatinshah** [comment]
I have verified that the below code is an AND filter. What's the one for OR filter?

`filter=['DFP_REQUEST_SOURCE==Dynamic Allocation with no DFP competition', 'DFP_REQUEST_SOURCE==No Dynamic Allocation'],`

**Comment by DeanLukies** [comment]
today that style of filter will not work in the API; only simple filters as shown here https://developers.google.com/ad-exchange/seller-rest/filters

I do not have any indication of if or when that may change.
