### ISSUE TITLE
Large reports

### ISSUE THREAD

**Issue by jemtech** [googleads/googleads-adxseller-examples#7]
Hello,
Based on "GenerateReport.java" we try to query:
Metric: "AD_REQUESTS", "AD_REQUESTS_COVERAGE", "EARNINGS", "MATCHED_AD_REQUESTS", "MATCHED_AD_REQUESTS_RPM", "CLICKS", "COST_PER_CLICK" 
Dimension: "MONTH", "AD_UNIT_ID", "AD_UNIT_NAME", "DSP_ID", "DSP_NAME", "ADVERTISER_NAME", "AD_UNIT_SIZE_NAME", "BID_TYPE_CODE", "TRANSACTION_TYPE_NAME", "COUNTRY_CODE", "COUNTRY_NAME"
If our time range is >5 days we receive:
"domain" : "global", "message" : "Internal Error", "reason" : "responseTooLarge"

**Comment by DeanLukies** [comment]
Hi,
Try to stick to less than 8 dimensions and 12 metrics; this will help some but may not allow you to query many days.
You may need to do a daily request and join them at your end.
